// Generated by Selenium IDE


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CitilinkTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @org.junit.jupiter.api.Test
    public void httpswwwcitilinkru() {
        driver.get("https://www.citilink.ru/");
        driver.manage().window().setSize(new Dimension(974, 1040));
        driver.findElement(By.xpath("//span[contains(.,\'Войти\')]")).click();
        driver.findElement(By.xpath("//button[contains(.,\'Войти по паролю\')]")).click();
        driver.findElement(By.xpath("//span[contains(.,\'E-mail\')]")).click();
        driver.findElement(By.name("login")).click();
        driver.findElement(By.name("login")).sendKeys("nariman.gumerov@mail.ru");
        driver.findElement(By.name("pass")).click();
        driver.findElement(By.name("pass")).sendKeys("Nari01121990");
        driver.findElement(By.xpath("//form/div/div[2]/button/span")).click();
    }
}
